version: '3.1'
services:
  zookeeper:
    container_name: docker-kafka_zookeeper
    image: zookeeper:3.6
    ports:
      - 2181:2181
    networks:
      - docker-kafka-network
  kafka:
    container_name: docker-kafka_kafka
    build: .
    environment:
      KAFKA_VERSION: 2.6.1
      SCALA_VERSION: 2.12
    ports:
      - 9092:9092
    volumes:
      - /tmp/kafka:/kafka
    networks:
      - docker-kafka-network
    depends_on:
      - zookeeper
  kafka-manager:
    container_name: docker-kafka_kafka-manager
    image: kafkamanager/kafka-manager:latest
    ports:
      - 9010:9000
    environment:
      ZK_HOSTS: zookeeper:2181
      KAFKA_MANAGER_AUTH_ENABLED: "true"
      KAFKA_MANAGER_USERNAME: admin
      KAFKA_MANAGER_PASSWORD: admin
    networks:
      - docker-kafka-network
    depends_on:
      - kafka
      - zookeeper

networks:
  docker-kafka-network:
    driver: bridge
